### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by codepathreview** [rrazong/SimpleToDo#1]
Hello Richelle, 

Thanks for submitting your pre-work but your current submission is incomplete. Can you please review the section in the pre-work about [the readme](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) for your project? 

In particular, be sure to use this [README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true), check off your completed features (`[x]`) and [include a recorded app walkthrough with LiceCap](http://www.cockos.com/licecap/). 

Please re-submit your project on your [application dashboard](https://apply.codepath.com/dashboard/) and reply back on this issue once that's completed.

**Comment by rrazong** [comment]
Thanks!

I've all of the following per your reminder:
- added a README
- checked off my completed features
- included a recorded app walkthrough
- resubmitted on the Application Status dashboard

I plan to implement some of the extra features before the September 30 deadline.

Rich
